export   const testData = [
    {  
      firstName: 'John',
      lastName: 'Doe',
      dateOfBirth: '1985-05-10',
      startDate: '2010-03-15',
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      department: 'human ressources',
    },
    {
      firstName: 'Jane',
      lastName: 'Smith',
      dateOfBirth: '1990-12-20',
      startDate: '2012-08-05',
      street: '456 Elm St',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      department: 'Marketing',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'teo',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'felip',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'adrian',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'c arl',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'sly',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'Johnson',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },
    {
      firstName: 'Robert',
      lastName: 'cool',
      dateOfBirth: '1978-08-03',
      startDate: '2005-11-30',
      street: '789 Oak St',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      department: 'sales',
    },

   
  ];